# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_news', '0002_auto_20170920_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='data',
            field=models.DateField(default='2017-09-20'),
        ),
    ]
